rule all:
    input: expand('results/{sample}.sorted.bam.bai', sample=['sampleA', 'sampleB'])
        
rule samtools_sort:
    input:
        bam = 'samples/{sample}.bam'
    output:
        sorted_bam = 'results/{sample}.sorted.bam'
    conda: 
        'envs/samtools_env.yml'
    shell:
        """
        samtools sort {input.bam} > {output.sorted_bam}
        """

rule samtools_index:
    input:
        sorted_bam = 'results/{sample}.sorted.bam'
    output:
        bai = 'results/{sample}.sorted.bam.bai'
    conda: 'envs/samtools_env.yml'
    shell:
        """
        samtools index {input.sorted_bam} > {output.bai}
        """